Repository TaskForce47/TF47-Corescripts, pull requests merged in 2020-08, with the labels that each got.

#16 Adding feature requests
  CfgDebriefing.hpp
  functions/core/fn_safezone.sqf
  functions/core/fn_settings.sqf
Labels: WIP

#18 Breaking changes! Split unit traits to crew and pilot for flying vehicles
  functions/script_common.hpp
  functions/whitelist/fn_addSlotTraits.sqf
  functions/whitelist/fn_checkSlotTrait.sqf
Labels: enhancement

#19 Prevent side chat when unconscious
  functions/ace/fn_initPlayer.sqf
Labels: enhancement

#20 missign traits
  functions/whitelist/fn_initSlotTrait.sqf
Labels: bug
